/* tslint:disable */
/* eslint-disable */
/**
 * ZapCap API
 * API for generating amazing subtitles for your videos
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export * from "./zapcap";
